# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:20
from django.db import migrations, models
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(
        username='admin',
        email='',
        password='[[ hooks.password ]]'
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
